version: '3'
services:
  classifier:
    container_name: classifier
    volumes:
      - /home/vadim/work/work_level_classifier:/app
    build: .
    depends_on:
      - db
    networks:
      - classifier_net
    ports:
      - "27363:8501"
    working_dir: /app
    command: ["streamlit", "run", "app.py"]

  db:
    container_name: postgres_wsgu
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/data/postgres
      - ./classifier/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - classifier_net
    # ports:
    #   - "5433:5432"

networks:
  classifier_net:
    driver: bridge

volumes:
  postgres:
    driver: local
